default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: phase-3-sinatra-react-project

test:
  <<: *default
  database: phase-3-sinatra-react-project

production:
  <<: *default
  database: phase-3-sinatra-react-project
  